spring:
  application:
    name: asset-service
  cloud:
    azure:
      storage:
        queue:
          enabled: false
        fileshare:
          enabled: false
        blob:
          enabled: true
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
          account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
          endpoint: ${AZURE_STORAGE_ENDPOINT}
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: [ health ]
springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    enabled: true
    path: "/docs"
